language: cpp
compiler: gcc

before_install:
  - git clone --depth=50 --branch=master http://github.com/Kirill-NiK/small_programms.wiki.git ./../small_programms.wiki/
  - openssl aes-256-cbc -K $encrypted_299f80385780_key -iv $encrypted_299f80385780_iv -in l.enc -out ~/.netrc -d
  - chmod 600 ~/.netrc
env:
  - CONFIG=debug   PROJECT=fun_count   VERA=false  TESTS="./fun_count"


install:
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get update -qq; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50; fi
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
  - sudo add-apt-repository "deb http://ppa.launchpad.net/beineri/opt-qt55-trusty/ubuntu trusty main"
  - sudo add-apt-repository ppa:smspillaz/verapp-latest -y
  - sudo apt-get update
  - sudo apt-get install libboost-system-dev libboost-wave-dev tcl
  - sudo apt-get install vera++
  - sudo apt-get -f install libpango-1.0-0 qt55base qt55svg qt55script libgl1-mesa-dev -y
  - . /opt/qt55/bin/qt55-env.sh

script:
  - gcc --version
  - qmake --version
  - if [ "$VERA" = "true" ]; then tclsh buildScripts/vera++/generatePaths.tcl; fi
  - if [ "$VERA" = "true" ]; then vera++ --error -p allRules --root buildScripts/vera++ <buildScripts/vera++/params; fi
  - qmake $PROJECT.pro CONFIG+=$CONFIG
  - make -j2
  - ls -A
  - cd ./../small_programms.wiki
  - ls -A
  - echo -e 'Test coverage and method Information for QReal project\nCommit: ' "$TRAVIS_COMMIT" '\nPull request: ' "$TRAVIS_PULL_REQUEST" '\n Branch: ' "$TRAVIS_BRANCH" '\nTravis OS: ' "$TRAVIS_OS_NAME" > Home.md
  - cat Home.md
  - git config --global user.name "Kirill-NiK"
  - git config --global user.email nikolskiy.kirill.andreevich@gmail.com
  - git commit Home.md -m 'the statistic for QReal master commit: "$TRAVIS_COMMIT"'
  - git push
notifications:
  email:
    recipients:
      - nikolskiy.kirill.andreevich@gmail.com